### ISSUE TITLE
Nepotrebno kreiranje objekta

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#1]
https://github.com/gkovac42/plava-tvornica-projekt/blob/92cf85522abe42fcd56e33c0a8ade13302069d83/app/src/main/java/com/example/goran/mymoviedb/login/LoginPresenter.java#L51

pri svakom pozivu kreiras novi listener.

**Comment by gkovac42** [comment]
Je, moja greška, zbog brzanja.
