### ISSUE TITLE
Android Lifecyle

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#10]
Nisi primijenio znanje o android lifecyleu. Zašto?

**Comment by gkovac42** [comment]
Činilo mi se kao overkill za ove potrebe, ali mogu i na taj način pokušati.

**Comment by wideking** [comment]
U svakom presenteru koji si napisao pozivaš on destroy. To ne bi morao pisati da si implementirao base presenter / interactor sa lifecycleom, tako da ti je to primjer da ima potrebe. Manje koda za održavanje, manje gresaka

**Comment by gkovac42** [comment]
Ok! Prepravit ću to.

**Comment by gkovac42** [comment]
Malo mi je ovo nejasno još. Znači imam base presenter i interactor interface i implementacije koje se brinu o lifecycle-u i koje extendaju svi ostali presenteri / interactori? Kako povežem lifecycle s odgovarajućim activity i fragmentima? Moram imati i nekakav base view?

**Comment by wideking** [comment]
Možeš sa base viewom ili još bolje povežeš ih u dagger modulu. Tamo gdje provideš interactor staviš da ti metoda prima i activity i onda samo kažeš da je tvoj interactor observer tog activity-a :)

**Comment by wideking** [comment]
Vjerojatno ti je dovoljno da samo interactor bude lifecycle aware, ovisno o tvojoj implementaciji i stvarima koje radis u presenteru

**Comment by gkovac42** [comment]
Shvaćam kako to izvesti, ali ako interactor izravno promatra activity, zar ne ide to protiv ideje mvp-a da data i view ne smiju biti izravno povezani?

**Comment by wideking** [comment]
Generalno rečeno u pravu si, ovime interactor zna da ga netko kontrolira. Prakticki gledano, nije naruseno to pravilo jer se to sve casta u lifecycle i interactor nema referencu na view, dok Activity ima na njega referencu, tj ima referencu na LifecycleObserver interface. Realno gledajući, tu referencu ima Activity kao android komponenta na drugu android android komponetu, nisi prekrsio pravilo da si svoj View interface vezao sa Interactor komponentom ( u interfaceu nemas deklarirano nista sto ih povezuje) .

Malo je zbunjujući odgovor, reci ako trebam dodatno pojasniti.

**Comment by gkovac42** [comment]
Ok, mislim da kužim.
