### ISSUE TITLE
Layouti

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#11]
https://github.com/gkovac42/plava-tvornica-projekt/blob/4fd2bfa919ce7d8ff84156352a0c82d83771d0b9/app/src/main/res/layout/fragment_movie_details.xml#L2

Ovaj view sigurno može biti manje kompleksan. Recimo framelayout ti ne treba.  Dobra stvar sto si koristio linear layout a ne relativne. Bolja stvar bi bila da možda to zamjenis sa constraintom. Najbolje riješenje bi bilo da prepravis na recyyler. Scroll view je gadna stvar. Ovdje može proći jer sadržaj nije kompleksan ali uvijek se trudi kompleksne stvari riješiti sa recyclerom. 

Znaš li možda nešto o kompleksnosti layouta? Čemu se treba težiti? Kako android zna gdje koji layout ide, kako on to izračuna te kako in vodi brigu o izmjenama stvari na screenu, recimo kod promjene veličine slike, teksta Itd?

**Comment by gkovac42** [comment]
Mislio sam da su layouti jednostavni i da tu nema puno filozofije ali sam sad skužio da već kad je malo više stvari na screenu nastaje zbrka :)
Još eksperimentiram s ovim i ništa to još nije konačno. Probam si svaki dan izdvojiti malo vremena za proučavanje xml-a i dizajna.

**Comment by wideking** [comment]
Probaj naći odgovore na pitanja koja sam ti postavio :)

**Comment by gkovac42** [comment]
Trebalo bi težiti širokim, a izbjegaviati duboke layoute - dakle što manje ugnježđenih parent layouta i komponenata.

Ovako sam shvatio proces: Android slaže layout u 2 koraka - u onMeasure() izmjeri veličinu view-a onako kako smo je odredili. Zatim u onLayout() slaže view-e i prilagođava njihovu veličinu layout-u. To može obaviti u 1 ili 2 pass-a, ovisno o kompleksnosti. U prvom pass-u odredi pozicije, a u drugom, ako je potrebno prilagodi veličinu poziciji.  Treba izbjegavati drugi pass ako je moguće. Npr. Relative layout uvijek ide u 2 pass-a, dok Linear ide u 1, osim ako se ne koristi weight.

Constraint layout sam do sada izbjegavao iz navike, ali vidim da ga hvale pa ću probati s njim. 
A što se tiče recyclera, nisam ni znao da se može koristiti na taj način. Kako to onda funkcionira? Kao zamjena za scrollview? Jel mogu kombinirati recycler i constraint?

**Comment by wideking** [comment]
Dobro si shvatio. Važno je znati da će se onMeasure odnosno onLayout pozvati kada bilo tko od childova kaže da je invalidate-an. Zbog toga želimo da imamo što manju dubinu, jer najmanja izmjena child-a utjeće na cijelu gradnu view hijerarhije. To je zgodno imati na umu :)

Constraint je fenomelanalan ali treba dosta vremena da se priviknes na rad s njime. I ima svojih bugova. Recimo wrap content ga zna zezati, ali sve se da riješiti. Ja sam na jednom projektu zamjenio recyclere i kompleksnije viewove sa constraitom i na očigled ubrzao app, a nije mi se činilo da lagga. 

U recycler možeš postaviti kakav kod layout želiš. Recycler se samo brine da prikaže dobar viewholder i nudi mogućnost scrollanja ( kad kažem samo mislim na ogroman posao koji napravi u pozadini za nas).

Podijeliš svoj ekran u viewholdere - slično kako i do sada imaš, samo ti je sve u jednom layout-u. Obično je jedan view holder jedna informacijska sekcija odnosno dio koji se reusa kod novog prikaza.  Ako reusanje view-a na tom screenu ne postoji onda si zaokružiš viewholder na infomacijsku cijelinu. Mislim da bi kod tebe jedna informacijska cjelina bio opis filma, pa slika te onda onaj drugi recycler view. Na taj način postižeš da ti se view koji nije prikazan, a ima ih, ne bude u memoriji. Striktno za tvoj screen možda ne bi bilo benefita, ali za veći screen, koji sadrži puno više informacija sigurno bi bilo jer bi postojalo dosta viewova koji nisu na ekranu, pa ne bi morali biti u memoriji.

**Comment by gkovac42** [comment]
Super. Ovo za recycler ću zapamtiti ali neću sad komplicirati s tim. Pokušat ću ovu hrpu nabacanih layouta koje trenutno imam zamjeniti sa constraintom što je više moguće.

**Comment by gkovac42** [comment]
Hm...prebacio sam dosta toga na constraint, ali opet mi treba Frame layout kao root, tako prikažem progress bar u sredini a ostalo sakrijem/prikažem kad je spremno. Ima neki bolji način za to postići?

**Comment by wideking** [comment]
Za prikaz progress bara koristi fragment dialoge :)

**Comment by gkovac42** [comment]
Jao...zadubim se u jedno rješenje i onda se ne sjetim nečeg ovako očitog :)
