### ISSUE TITLE
Korisnički podaci

### ISSUE THREAD

**Issue by gkovac42** [gkovac42/my-movie-db#13]
Kako je najbolje pohraniti podatke za aktivnog korisnika koji mi trebaju za requestove prema apiju (sessionId, accountId itd.)? Je li pametno držati ih u statičnoj varijabli koja bi bila uvijek lako dostupna?

**Comment by wideking** [comment]
Statična varijabla je u redu ali pod uvijetom da u nju ne cachiras response s diska - drugim rijecima, uvijet je da imas samo jedan flow podataka, da se ti podaci ne nalaze na vise mjesta. Takoder, varijable trebaju biti razumiljive, najbolje da su wrapena u neki objekt, cisto da se zadrzi konzistentnost kada se podaci mijenjaju.
