### ISSUE TITLE
Job Dispatcher i Job Service

### ISSUE THREAD

**Issue by gkovac42** [gkovac42/my-movie-db#14]
Odlučio sam koristiti Firebase Job Dispatcher za notifikacije. E sad, shvatio sam po tutorijalu kako to funkcionira, više manje, samo nisam siguran kako mi se to uklapa u MVP. U kojem layeru bi bio JobService? Kada hoću u onStartJob() dohvatiti podatke jel moram ići preko interface-a i interactora pa injectati cijeli interactor ili mogu izravno od helper klase zatražiti što mi treba?

**Comment by wideking** [comment]
Za stvari koje nisi siguran najsigurnije ti je to tretirati kao vlastiti modul koji ima model view presenter. Dakle u svome job dispatcher servisu zoveš interactor odnosno presenter da obave logiku.  Stvari dodaj u job scheduler kako iz viewa nekog aktivitija jer mi se čini da ti treba kontekst za to. Ako ne treba onda iz prezentera možeš, jer svakako presenter treba reci viewu da to odradi. Ti ovo pomoglo?

**Comment by gkovac42** [comment]
Ok, imam presenter i interactor. View bi u ovom slučaju bio service?

Napravio sam tako da u JobService-u preko presentera/interactora dohvatim filmove koji su na listi i onda usporedim trenutni datum sa svakim filmom i pustim notifikaciju sa kratkim opisom filma. Sad bi  valjda trebao pokrenuti taj service iz nekog activity-a, tj. provjeriti da li je već pokrenut...namjestiti interval u kojem da radi provjeru i updejtati service kad se dodaju novi filmov na listu.

**Comment by wideking** [comment]
Čini mi se da si napravio "naopako". Job scheduler se ne može dugotrajno vrtiti u pozadini, tj moraš računati da imaš svega sekundi dvije da se tvoj posao na njemu odradi. U njemu bi trebao minimalne stvari raditi. On bi trebao samo pokrenuti da se pokaže notifikacija, a ti bi tamo gdje se pretplaćuješ na filmove trebao napraviti task i reći kada da se on pokrene :)

**Comment by gkovac42** [comment]
Misliš da svaki put kad dodam film u favorite tj. wishlist-u, za njega napravim task koji će baciti notifikaciju na zadani dan?

**Comment by wideking** [comment]
Tako je, onda znaš da korisnik želi znao za taj film, ne moraš ih pretraživati samo moraš reci kad će se notifikacija pokazati

**Comment by gkovac42** [comment]
Stvarno sam išao naopakom logikom...ja sam radio service za sve filmove na listi koji se ponavlja svaki dan i provjerava je li koji izašao. A ništa, probat ću sad ovako, dosta toga mogu reciklirati pa ne bi trebalo potrajati .

**Comment by gkovac42** [comment]
E još jedno pitanje, da ne bi opet krivo nešto napravio. Kad pravim task u dispatcher job builder-u, zakažem ga sa .setTrigger(Trigger.executionWindow(windowStart, windowEnd)) tako da windowStart bude razlika dana prikazivanja filma i trenutnog vremena. Jel mogu nekako izravno odrediti datum za trigger?

**Comment by wideking** [comment]
Dobru si logiku napisao, moras mu reći razliku trenutnog vremena i sadašnjeg, tako da mislim da mu nemožeš izravno predati datum kao parametar.

**Comment by gkovac42** [comment]
Ok, onda mislim da sam gotov s ovim.

Išao sam na favorite, tako da poziv bude prema apij-u a ne lokalno. Kad se film doda u favorite provjeri se je li već izašao. Ako nije zakaže se notifikacija na dan izlaska. Ako izlazi na dan kad je dodan notifikacija se prikaže odmah.

**Comment by wideking** [comment]
To je to :)
