### ISSUE TITLE
Podrška za tablet / različite dpi

### ISSUE THREAD

**Issue by gkovac42** [gkovac42/my-movie-db#15]
Počeo sam s ovim danas, napravio nekoliko land layout-a. Izvukao sam sve mjere u dimens file pa sam mislio prilagođavati veličinu za različite uređaje i testirati kako to izgleda. E sad, osim onih standardnih mdpi, hdpi, xhdpi itd. tih standarda ima jako puno. Što bi sve trebao pokriti? Možeš mi dati neke smjernice da znam odakle krenuti, na što se fokusirati a što preskočiti? :)

**Comment by wideking** [comment]
Prouči ovaj link https://developer.android.com/guide/practices/tablets-and-handsets.html
 Na ovom linku ti je pojašnjeno kako možeš postaviti različite resurse : https://developer.android.com/guide/topics/resources/providing-resources.html

Ne želiš nužno raditi layout za land, jer ti to ne znači da se on učitati na tabletima. Za tablete želiš koristiti  oznaku kao što je sw600 ili sl. (biti će ti jasnije kada pročitaš linkove).

Dobro je izvući dimenzije u fileove jer ti omogućuje prilagodbu na različitim ekranima, ali budući da su sve vrijednosti u dp ili sp obično dobro skaliraju pa nije potrebno mijenjati( barem ne po dpi-u).  Mislim da ti ovdje neće to biti potrebno, da ćeš zapravo uvijek raditi specifičan layout za tablet. Međutim, ono što je dobro napraviti je assete stavljati u više veličina. Pod time mislim na assete koji nisu vektori. Razlog za ovo je što u suprotnom se može desiti da na većim ekranima ikonice izgledaju mutno. Zato obično imamo puno drawable - NEŠTOdpi foldera.  Znaš kako android određuje koji asset će uzeti ako nema odgovarajući asset? Uzima prvi veći. Idealno bi bilo imati od svake grupe asset ali to povećava app.
U pravilu stavljamo slijedeće  : 
* mdpi ( ovo možemo preskočiti jer nema baš ovakvih mobitela) 
* hdpi (prvi asset iznad mpdi-a, a mdpi ti je obično baseline verzija). Ovo bi ti bili stariji mobiteli kod od nekih 4" sa lošijim ekranom ( dpi ne ovisi samo o dimenziji ekrana nego i matrici ekrana). 
* xhdpi
* xxhdpi ** ako se postavlja xxxhdpi ovo bi se moglo preskočiti na uštedu prostora. Sve ovisi o volji za optimizacijom :)
* xxxhdpi *** ovo koriste jako dobri ekrani, tipa samsung s8 ili neki super dobar tablet.

Rezolucije slika su čudna stvar. Evo meni jedna fascinantan primjer :  Par tableta koje sam ja isprobao tipa nexus iz 2015 je koristio xhdpi slike, a ima ekran od 8" ili 9"  sa visokom rezolucijom.  Neki manji i stariji flagship mobiteli učitavaju xxhdpi.
Generalno govoreći nema nekog znatnog pravila, moramo podržavati što više i gledati da to ispadne lijepo na svim tipovima ekrana. Obično ti je to try - error metoda, gdje radiš izmjene kad uočiš da negdje nije dobro pa dodaš poseban asset za taj tip.

Postoji lakši i bolji način handlanja asseta a to je da se koriste svg fileovi. To su ti vektorske slike. Naravno, nije sve moguće prebaciti u vektore i za to obično trebaš dizajnera koji će ti dati takve assete, ali pomogne ako većinu možeš prebaciti. Manje brige, smanjiš veličinu apk-a i svi sretni. Sry za long post :D

**Comment by gkovac42** [comment]
Kod sw600, 600 je vertikala ekrana? Kao u 1024x600? Koristio sam vektorske assete uglavnom tako da sa tim ne bi trebalo biti problema. 

Ma ja sam eksperimentirao sa ovim modelim što nudi emulator u Android Studiju. Većina mi je prihvatila i lijepo skalirala land layout-e pa sam pretpostavio da su oni defualtni za tablet. Dok mi recimo Nexus 10 ne prihvaća ništa i uvijek je sve sitno. 

Kad smo već kod emulatora, jesi imao iskustva s nekim od alternativa na AMD-ovim procesorima? Negdje čitam da su ok, a negdje da su katastrofa spori.

**Comment by wideking** [comment]
Uopće nisam dobio mail da si pisao. Izvini. sw označava minimum width dakle horizontalu. 

Nekada davno sam koristio genymotion, on je bio super na amd-u. Nisam koristio ništa drugo, otkako je google ubrzao svoj emulator.
