### ISSUE TITLE
Retrofit i Api problem

### ISSUE THREAD

**Issue by gkovac42** [gkovac42/my-movie-db#16]
https://developers.themoviedb.org/3/movies/get-movie-account-states

Sad sam ovo primjetio. Problem je u tome što API vraća različit tip podatka za isto polje - rated može biti boolean ili Rated objekt. U model klasi za retrofit moram odrediti tip podatka, pa ako stavim boolean baci mi exception kada je objekt i obratno. Jel mogu jednostavno nekako retrofitu reći da očekuje oba tipa ili moram hvatati exception?

**Comment by wideking** [comment]
Morati ćeš napraivti custom type za taj field. Ovo nije samo mana retrofita
već je mana jave. Jednom kad kazes kojeg je tipa nesto nema promjener jer
svi racunaju da ce to biti tog tipa.  Dobra stvar je sto mozes napraviti
custom parser za taj tip podatka( olaksas si pa si napravis sam custom
objekt).

Evo ti primjera, čak je i za tvoj api :
https://stackoverflow.com/questions/42673604/same-field-has-two-different-types-gives-trouble-with-gson-converter-for-retrofi

2018-02-13 16:30 GMT+01:00 Goran Kovač <notifications@github.com>:

**Comment by gkovac42** [comment]
Ok, kužim to sad. Hvala na linku :)
