### ISSUE TITLE
Memory leakovi

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#2]
U interaktoru postoje memory leakovi.

**Comment by gkovac42** [comment]
Nisam još do kraja implementirao interaktore, samo sam isprobavao da li rade osnovne funkcionalnosti. Popravit ću.

**Comment by wideking** [comment]
Primjetio sam da još imaš memory leakove u interaktorima.

**Comment by gkovac42** [comment]
Zbog listenera?

**Comment by wideking** [comment]
da, imas listener unutar innter klase. Te listenere ne mozes izbjeci, ali mozes unistiti observer kada se on destroy pozove.

**Comment by wideking** [comment]
Zatvori kada budeš mislio da je task suvišan.

**Comment by gkovac42** [comment]
Isprobavao sam razlicite nacine kako ovo sto jednostavnije rjesiti. Na kraju sam napravio BaseListener kojeg svi extendaju i kojeg pocistim u BaseInteractor-u, u lifecycle aware metodi. Nesto kao i sa disposanjem observablea.
