### ISSUE TITLE
Nedostaju datoteke

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#3]
Na git-u ti se nalazi samo app module, fali ti gradle settings za cijeli app. Ako nisi siguran što sve treba ići, probaj pullati projekt u drugi folder i otvoriti ga u android studiju :) 
Obavezno si prvo podesi .gitinore file, pa dodaj u git ostale datoteke

**Comment by gkovac42** [comment]
Ups :)
Budem popravio.

**Comment by gkovac42** [comment]
Što bi sve trebao ignorirati? trenutno imam ovo:

*.iml
.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.idea
.DS_Store
/build
/captures
.externalNativeBuild

**Comment by wideking** [comment]
.gradle ne bi trebao ignorirati, to je tvoj build file. U njemu su sadzane korisne informacije kao podaci sto buildas, koje lovove koristiš etc.

**Comment by wideking** [comment]
Možemo zatvoriti?
