### ISSUE TITLE
Provjeri zahtjeve appa

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#4]
Provjeri specifikaciju koju sam ti napisao. Ako se ne varam napisao sam da moras podržavati tablet i oba načina rada. Jesi li razmislio kako ćeš to implementirati?

**Comment by gkovac42** [comment]
Da budem iskren, nisam u životu koristio tablet :)
Ako je u biti ono što mislim da je, mobitel s većim screenom, planirao sam za vodoravnu orijentaciju malo drugačije posložiti elemente sučelja, kombinirati dva fragmenta u jedan screen gdje to ima smisla i sl.

Svakako sam mislio krenuti od podrške za manje formate, pa onda kombinitrati i prilagođavati većima - tako mi se čini logično. Ako misliš da bi trebao ići drugim pristupom slobodno reci kako bi bilo pametnije.

**Comment by wideking** [comment]
To je to, glavna razlika je da probaš koristiti fragmente i proučiti kako se kreiraju layouti za određeni tip - hint prouči resource foldere, android puno stvari riješi za tebe :) fragmenti su korisni jer u tom slučaju funkcionalnost držiš u njima pa nemaš problem da imaš kod koji nije aktivan u activitiju
