### ISSUE TITLE
Interactor interface

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#5]
https://github.com/gkovac42/plava-tvornica-projekt/blob/92cf85522abe42fcd56e33c0a8ade13302069d83/app/src/main/java/com/example/goran/mymoviedb/data/Interactor.java#L14

Meni se ovakav pristup osobno ne sviđa. Ne bi volio u svom projektu imati klasu koja ima milion inner klasa koje definiraju tuđe funkcionalnosti. Ovo se Obično radi unutar klase čiju funkcionalnost definiraš ili u paketu. Ono što više preferiram zbog preglednosti je imati interactore u vlastitom paketu i onda izvuci interface. Ako vidiš neki drugi benefit tvoja pristupa, reci mi, tu smo da učimo :)

**Comment by gkovac42** [comment]
Ovdje sam bio malo ljen, priznajem. Pošto imam više interaktora nisam znao kako da nazovem njihove interface, pa mi je ovo prvo palo na pamet. Nije baš najbolje rješenje, popravit ću.

**Comment by gkovac42** [comment]
Jel bi bilo bolje rješenje da dodam Interactor interface u Contract, tako da onda on ima View, Presenter i Model interface? Vidio sam da tako neki rade.

**Comment by wideking** [comment]
Interactor bi trebao biti nevezan uz neki contract. On predstavlja podatke, s kojima bi svi trebali moći raditi. Druži ga u nekom contractu bi se moglo protumačiti da je taj interactor striktno vezan uz implementaciju tog contracta sto obično nije slučaj, zar ne?

**Comment by gkovac42** [comment]
Jedno banalno pitanje u vezi ovoga :)
Recimo da napravim kao što si rekao...kako da onda nazovem interactor interface i implementacije? Ne nalazim ništa konkretno na netu o tome osim npr. LoginInteractor i LoginInteractorImpl, a to mi je malo bez veze.

**Comment by wideking** [comment]
Da, obično se tako nazivaju. Malo je zbunjujuće jer imaš Impl ali nekako se lako navikneš na to. Imaš možda neki drugi problem s time osim imenovanja?

**Comment by gkovac42** [comment]
Trenutno nemam. Bacam se na refactoring :)
