### ISSUE TITLE
Nepotreban parametar u konstruktoru

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#6]
https://github.com/gkovac42/plava-tvornica-projekt/blob/4fd2bfa919ce7d8ff84156352a0c82d83771d0b9/app/src/main/java/com/example/goran/mymoviedb/movies/adapters/CastAdapter.java#L27

**Comment by gkovac42** [comment]
Prosljeđujem podatke kroz konstruktor trenutno. Jesi mislio da je ova metoda ispod nepotrebna? Nju ne koristim.

**Comment by wideking** [comment]
Bolje je da imas prazan konstruktor. Metoda je korisnija jer to znaci da možeš mijenjati podatke bez da radiš novi adapter

**Comment by gkovac42** [comment]
Ok, ima smisla.
