### ISSUE TITLE
Podaci iz activity-a

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#7]
https://github.com/gkovac42/plava-tvornica-projekt/blob/4fd2bfa919ce7d8ff84156352a0c82d83771d0b9/app/src/main/java/com/example/goran/mymoviedb/movies/home/HomeActivity.java#L125

Ovakve stvari ti je bolje odmah na inicijalizaciji proslijediti presenteru.

**Comment by wideking** [comment]
https://github.com/gkovac42/plava-tvornica-projekt/blob/4fd2bfa919ce7d8ff84156352a0c82d83771d0b9/app/src/main/java/com/example/goran/mymoviedb/movies/list/MovieListPresenter.java#L38

Isti slučaj. Zbog ovoga ova klasu je teze testirati

**Comment by gkovac42** [comment]
Kako misliš da ne dođu iz activity-a ako idu kroz intent tj. u slučaju fragmenta kroz bundle?

**Comment by wideking** [comment]
Da ne pitas stalno view komponentu za tu vrijednost već da tu vrijednost predaš presenteru. Budući da su iz internet bundlea, vrijednost se neće mijenjati osim ako se ne igraš sa task afinitiima i pošalješ novi intent (nebitan use case u tvom slučaju)

**Comment by gkovac42** [comment]
Aha. Znači da ne pozivam stalno iz View-a nego da postavim odmah kroz konstruktor ili setter?

**Comment by wideking** [comment]
Nezgodno je kroz konstruktor jer ga injectas (ali je moguće). Obično se takvi podaci postave kroz initialize metodu.

**Comment by gkovac42** [comment]
Riješeno.

**Comment by wideking** [comment]
Nicely done :)
