### ISSUE TITLE
Podaci u fragmentu

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#8]
https://github.com/gkovac42/plava-tvornica-projekt/blob/4fd2bfa919ce7d8ff84156352a0c82d83771d0b9/app/src/main/java/com/example/goran/mymoviedb/movies/list/MovieListFragment.java#L37

U ovom slučaju podatke imaš na tri mjesta : 
presenter - on ih dohvati i modificira
Fragment
Adapter - on ih prikazuje.

Zaključi sto bi moglo bolje. Ovo ti je dobar pokazatelj da ako koristis tu listu u fragmentu za nešto drugo, vjerojatno u viewu obavljaš tuđi posao ;) (opcenito pričam)

**Comment by gkovac42** [comment]
Da, ovo to sam napravio da bi dobio item iz adaptera preko pozicije, ali sam mogao i u adapteru napraviti metodu koja ce mi vratiti item.

**Comment by wideking** [comment]
Krivo. Adapter kaže presenteru da se desio Kliček na taj i taj objekt i presenter dalje odluci sto s time. Ili se presenteru kaže pozicija pa on odluci. A ne da svi i imaju sve podatke, čemu onda priča o nekoj arhitekturi ako će svi raditi. A da ne govorimo o problemu da imaš dupli kod

**Comment by gkovac42** [comment]
Pa to sam i mislio - prosljediti item na kojem se desio klik kroz onClick listener.

**Comment by wideking** [comment]
Zatvori task kad napravis
