### ISSUE TITLE
Loše strukturiran interactor

### ISSUE THREAD

**Issue by wideking** [gkovac42/my-movie-db#9]
https://github.com/gkovac42/plava-tvornica-projekt/blob/4fd2bfa919ce7d8ff84156352a0c82d83771d0b9/app/src/main/java/com/example/goran/mymoviedb/movies/list/MovieListPresenter.java#L55

Iz ovoga ti mogu reci da je interactor loše napisan. Probaj sam zaključiti na sto mislim i kako to popraviti? Da li je potrebno exposati observable?

**Comment by gkovac42** [comment]
To sam napravio da ne ponavljam kod u Interactoru. Svaka lista ima drugačiji endpoint tako da moram zvati druge metode za retrofit, ali vrsta podataka i obrada je ista, što onda radim u ovoj getMovieList metodi. Za svaki poziv moram ponovo specifirati i broj starnice jer tako daju podatke. Činilo mi se da je bolje tu logiku rješiti u presneteru nego interactoru.

**Comment by wideking** [comment]
Dobro si mislio, lose si plementirao ideju. Promisli sto si mogao promjeniti, ja ću ti samo reci da to sve može biti obavljeno iz interactora. Tvoj presenter sad samo javlja interactori da to obavi, a može bez tog kompliciranja :)

**Comment by gkovac42** [comment]
Izvukao sam switch u interactor a preko presentera prosljeđujem category i page, tako da observable više nije exposan. Također sam napravio initPresenter metodu koja postavi category jednom na početku pa nema više stalnog pozivanja view-a. Preuredio sam itemClickListener u adapteru, tako da je lista je sada samo u presenteru. Ovako mi se čini bolje organizirano.

**Comment by wideking** [comment]
Puno bolje riješenje. Sada kada netko traži podatke odmah i dobije, ne zna za podatkovnu logiku što je plus jer ti pojednostavlja izmjenu :)
